### PR TITLE
Trivial typo

### PR DESCRIPTION
**Pull request by kinow**

### CODE REVIEW

**Comment by bdube** [comment]
Thank you, kinow. This project is still svn-based back at the ASF, so I've asked on our dev list how we're handling github pull requests.

**Comment by kinow** [comment]
Not a problem @bdube . Feel free to close and apply manually if necessary, or let me know if I need to send a patch or something.

**Comment by bdube** [comment]
Thanks for your patience, @kinow. Now that the git mirror has been nudged to catch up from the last 10 years, your pull request is reflecting more commits than it should. If you're willing to help us test our project's github integration, please try rebasing to see if that drops the pull request back down to your single commit. Thank you.

**Comment by kinow** [comment]
Not a problem @bdube 
Did a fetch --all and git status

```
git status
On branch trunk
Your branch and 'origin/trunk' have diverged,
and have 1383 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean
```

Tried a git pull, and then git push. Alternatively, I can simply delete my fork, re-fork, branch, and re-submit. Or feel free to apply the change manually and mark this as closed too :)

**Comment by bdube** [comment]
Ok, @kinow, I'll apply your patch manually. Thanks again.

**Comment by kinow** [comment]
By apply manually, I meant to say that you can fix the typo, commit with your user, and push, as this is such a simple trivial typo :-)

**Comment by bdube** [comment]
Committed with thanks in r1788345. When the mirror updates, I'd like to see if this PR automatically closes. If it doesn't, we'll have to ask @kinow to close it.

**Comment by kinow** [comment]
At Commons, if we want a pull request to be closed, we need to include some text in our commit messages such as

```
FIX-123: etc etc

This closes #1234567
```

Where 1234567 is the pull request number. Not sure if the forrest project uses similar set up. Just in case it does not automatically closes this PR, may be worth checking with the infra guys if it is possible to close it by this mention trick.

In case it is not closed @bdube, mention my user here at any time and I'll close the ticket :+1:

**Comment by bdube** [comment]
Thanks, @kinow. I believe those integrations are not yet activated for our project. Please close this request at your convenience.

**Comment by kinow** [comment]
Done. Thanks @bdube

**Pull request closed without merging**
